### ISSUE TITLE
Code .test(as.character) <- function() does not work

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.testthat#4]
I worked in **hyperSpec**. And code:
```r
.test(as.character) <- function() {
  context("as.character")

  test_that("as.character() works", {
    expect_is(as.character(faux_cell), "character")
  })
}
```
resulted in issues. I think it is due to `as.character` part.

When I commented the lines
```r
# .test(as.character) <- function() {
```

The test got merged to the previous test and the issue disappeared.

See code lines highlighted in https://github.com/cbeleites/hyperSpec/pull/211#discussion_r454600260

**Comment by cbeleites** [comment]
What happened here is that the test was attached to **base** `as.character()` since it cannot be attached to the anonymous function used in `setMethod()`. 

Solution: use internal "workhorse" functions instead of anonymous functions for methods. The tests can correctly be attached to these internal functions.
