### ISSUE TITLE
hySpc.testthat + Test Package (in RStudio) gives not identical section "Results" 2 times

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.testthat#8]
**hySpc.testthat** + Test Package (in RStudio) gives not identical section "Results 2 times. Is this expected?

I ran tests on **hyperSpec** (e.g.,  cbeleites/hyperSpec#255)

![image](https://user-images.githubusercontent.com/12725868/89358677-aea5df00-d6cc-11ea-9f5a-745e9fc79698.png)

**Comment by cbeleites** [comment]
No, this is not expected. Actually, it is less "not identical results 2 times" than "results cut in two".

This is fixed by calling `hySpc.testthat::unittest("PACKAGE", standalone = FALSE)" in the respective `tests/testthat/test_attached.R`.

Fixed this in 
- [x] **hySpc.skeleton** 
- [x] **hyperSpec**
- [x] **hySpc.ggplot2**
- [x] **hySpc.chondro**
